# Generated by Django 2.2 on 2019-05-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20190502_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='updates',
            new_name='updated',
        ),
    ]
